// <auto-generated />
using System;
using AttendanceStudents.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AttendanceStudents.Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251226121038_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.11");

            modelBuilder.Entity("AttendanceStudents.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("AttendanceStudents.Domain.Entities.Professor", b =>
                {
                    b.HasBaseType("AttendanceStudents.Domain.Entities.User");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Professor");
                });

            modelBuilder.Entity("AttendanceStudents.Domain.Entities.Student", b =>
                {
                    b.HasBaseType("AttendanceStudents.Domain.Entities.User");

                    b.HasDiscriminator().HasValue("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
